name: Test actions on push

on: [push]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install setuptools wheel twine
#    - name: Build and publish
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        cd yarrrml-translator
#        python setup.py -k rel sdist bdist_wheel
#        twine upload dist/*
    - name: Test with pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest yarrrml-translator
        cd test
        pytest
